### ISSUE TITLE
Frktest should follow Lune's style guide

### ISSUE THREAD

**Issue by CompeyDev** [itsfrank/frktest#6]
Currently, if I write my own frktest reporter using test APIs, it looks out-of-place from the rest of my codebase which follows Lune's naming conventions. Frktest uses snake_case naming for most things, while Lune does not. I also noticed some variable naming like `_state` in the console reporter for Lune, where a pattern of variables beginning with `_` in Luau signify variables that should not be made use of, not private variables.

The confusions are understandable since Lune's style guide is not very well documented elsewhere, the only "documentation" being the Lune codebase itself.

## Lune Style Guide
- Classes: PascalCase (defined as tables or functions which maintain a shared state of any sorts) 
- Variables: camelCase (defined as values which may be mutated)
- Constants: SCREAMING_SNAKE_CASE (defined as values which may not be mutated)
- Types: PascalCase
- Files: snake_case
- Semi-terse naming, identifiers should be unique and readable, while also not repeating themself (Eg: instead of PostgresClient.luau and PostgresServer.luau, store them under a module directory called postgres with an init.luau which exports both client.luau and server.luau; net instead of network)
- Modules should be preferably be grouped as a tree (eg: instead of RobloxInputMouseHandler.luau and RobloxInputKeyboardHandler.luau, inputHandlers/roblox/mouse.luau and inputHandlers/roblox/keyboard.luau; builders/X.luau instead of builders/XBuilder.luau)
- Formatting: width of 100, stylua defaults
- One-word variable names are discouraged, even in closures

**Comment by itsfrank** [comment]
Thank you for the suggestion, but will decline it. 

I follow style guides at work, and when I contribute to projects that have one (and if they don't I follow the style around where I'm working); but I much prefer working with snake case than pascal or camel, so in my hobby projects I use snake and avoid mixed-case styles.

As for the use of underscore, I agree `_state` is weird and that was intentional. It's a vestigial variable from when I was writing the first version of frktest. At the time, Lune's module caching was broken so I had to use a table to encapsulate module-scoped state (see [state.luau](https://github.com/itsfrank/frktest/blob/f61d4ed86e78f59dc1381da5caf424c0c3923353/src/state.luau#L1)). It was always intended to be temporary, when I eventually replace it, it will be with some non-global state to enable multiple separate test sessions in the same process. But I haven't had time (or reason) to get to that.

**Comment by CompeyDev** [comment]
It can be quite inconvenient for users to work with a library that does not align with the established conventions of the ecosystem, as it creates a disjointed appearance within the overall codebase. Lune and many of its associated packages already adhere to these standards.

Inconsistent casing across different parts of a project can lead to confusion and inconsistencies within the codebase. While enforcing a style guide is the job of opinionated linters -- which are not currently present for Luau -- I would request you to reconsider this decision.

**Comment by CompeyDev** [comment]
> It was always intended to be temporary, when I eventually replace it, it will be with some non-global state to enable multiple separate test sessions in the same process.

This would be great! One of my projects currently needs to use a typecast hack due to this design: https://github.com/0x5eal/semver-luau/blob/a62cac968dc32aac04cc6137205ccabaac08e2d8/.lune/test.luau#L9-L22

**Comment by itsfrank** [comment]
> This would be great! One of my projects currently needs to use a typecast hack due to this design

Interesting! I'll reach out when I re-work this to better understand the requirements

**Comment by itsfrank** [comment]
Btw, I updated the `init.luau` to remove the leading underscore: 9eaf262dece7797fb64b5468b84d4642ce1b5f37

`frktest._repoters.lune_console_reporter` is now `frktest.reporters.console_reporter`

The old path still works for backwards compatibility, but it will error won't be found via LSP and just points to `console_reporter`

frktest is also no longer a lune-exclusive library, lune is simply one of the supported runtimes
